//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class candidature
    {
        public string email { get; set; }
        public string nom { get; set; }
        public string Prenom { get; set; }
        public Nullable<int> phone { get; set; }
        public string Niveau_detude { get; set; }
        public Nullable<int> nombre_danne_exp { get; set; }
        public string Dernier_employeur { get; set; }
    }
}
